/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softestandantrop;

import DataBase.DataBase;
import Modelos.Antropometrista;
import Modelos.Estandarizacion;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class AgregarRonda extends javax.swing.JDialog {
    JDateChooser fecha;
    Inicio inicio;
    /**
     * Creates new form AgregarRonda
     */
    public AgregarRonda(Inicio inicio) {
        super(new JFrame(), true);
        initComponents();
        this.inicio = inicio;
        this.setLocationRelativeTo(null);
        
        ButtonGroup BtnGroup = new ButtonGroup();
        BtnGroup.add(rbTalla);
        BtnGroup.add(rbPeso);
        rbTalla.setSelected(true);
        
        fecha = new JDateChooser(new Date());
        fecha.setLocale(new Locale("es"));
        fecha.setDateFormatString("dd/MM/yyyy");
        fecha.setBounds(120, 102, 110, 20);
        fecha.setVisible(true);
	AgregarRonda.add(fecha);
        try{
            List<Estandarizacion> estandarizaciones = new DataBase().getAllEstandarizacion();
            Iterator ies = estandarizaciones.iterator();
            Estandarizacion es;
            while(ies.hasNext()){
                es = (Estandarizacion) ies.next();
            cboEstandarizacion.addItem(es.getId() + " - " + es.getEncuesta());
            }
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, 
                                    "Ocurrió un error al obtener las estandarizaciones.");
        }
        try{
            ArrayList supervisores = (ArrayList) new DataBase().getAllSupervisores();
            Iterator isup = supervisores.iterator();
            Antropometrista sup;
            while(isup.hasNext()){
                sup = (Antropometrista) isup.next();
            cboSupervisor.addItem(sup.getCodigo() + " - " + sup.getNombre());
            }
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, 
                                    "Ocurrió un error al ingresar los supervisores a la ronda");
        }
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarRonda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSupervisor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        rbTalla = new javax.swing.JRadioButton();
        rbPeso = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        BtnSelecionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboEstandarizacion = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Ronda");

        AgregarRonda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Ronda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Supervisor:");

        jLabel2.setText("Tipo de Ronda:");

        rbTalla.setText("Talla");

        rbPeso.setText("Peso");

        jLabel3.setText("Fecha:");

        BtnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Navigation Right.png"))); // NOI18N
        BtnSelecionar.setText("Agregar Antropometristas");
        BtnSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelecionarActionPerformed(evt);
            }
        });

        jLabel4.setText("Estandarización:");

        jLabel5.setText("Nombre:");

        javax.swing.GroupLayout AgregarRondaLayout = new javax.swing.GroupLayout(AgregarRonda);
        AgregarRonda.setLayout(AgregarRondaLayout);
        AgregarRondaLayout.setHorizontalGroup(
            AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRondaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarRondaLayout.createSequentialGroup()
                        .addGap(0, 130, Short.MAX_VALUE)
                        .addComponent(BtnSelecionar))
                    .addGroup(AgregarRondaLayout.createSequentialGroup()
                        .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(AgregarRondaLayout.createSequentialGroup()
                                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPeso)
                                    .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rbTalla)
                                        .addComponent(cboEstandarizacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboSupervisor, 0, 204, Short.MAX_VALUE)
                                        .addComponent(txtNombre)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarRondaLayout.setVerticalGroup(
            AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRondaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbTalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(BtnSelecionar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarRonda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarRonda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelecionarActionPerformed
        if(!txtNombre.getText().equals("")){
            this.dispose();
            new SeleccionarAntropometristas(this, inicio);
        }else{
            JOptionPane.showMessageDialog(null, "Debe colocar un nombre a la ronda.");
        }
        
    }//GEN-LAST:event_BtnSelecionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarRonda;
    private javax.swing.JButton BtnSelecionar;
    public javax.swing.JComboBox cboEstandarizacion;
    public javax.swing.JComboBox cboSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    protected javax.swing.JRadioButton rbPeso;
    protected javax.swing.JRadioButton rbTalla;
    protected javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
