/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softestandantrop;

import DataBase.DataBase;
import Modelos.Antropometrista;
import Modelos.RondaAntropometrista;
import Modelos.Sujeto;
import Validation.NotEmptyValidators;
import Validation.SoloNumeroValidator;
import Validation.TiposValidator;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class AgregarAntropometrista extends javax.swing.JDialog {

    /**
     * Creates new form AgregarAntropometrista
     */
    int idRonda = -1;
    List<Sujeto> sujetos;
    public AgregarAntropometrista() {
        super(new JFrame(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        txtCodigo.setInputVerifier(new SoloNumeroValidator(this, txtCodigo, "Ingrese el código."));
        txtNombre.setInputVerifier(new NotEmptyValidators(this, txtNombre, "Ingrese el nombre."));
        txtTelefono.setInputVerifier(new NotEmptyValidators(this, txtTelefono, "Ingrese el telefono."));
        this.setVisible(true);
    }

    AgregarAntropometrista(int idRondaSeleccionada, List<Sujeto> allSujetosByRonda) {
        super(new JFrame(), true);
        initComponents();
        this.idRonda = idRondaSeleccionada;
        this.sujetos = allSujetosByRonda;
        this.setLocationRelativeTo(null);
        txtCodigo.setInputVerifier(new SoloNumeroValidator(this, txtCodigo, "Ingrese el código."));
        txtNombre.setInputVerifier(new NotEmptyValidators(this, txtNombre, "Ingrese el nombre."));
        txtTelefono.setInputVerifier(new NotEmptyValidators(this, txtTelefono, "Ingrese el telefono."));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAgregarAntropometrista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        ckSupervisor = new javax.swing.JCheckBox();
        txtTelefono = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Antropometrista");

        pAgregarAntropometrista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Antropometrista", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Telefono:");

        jLabel4.setText("Codigo:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        ckSupervisor.setText("Supervisor");

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Delete.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setName("BtnCancelar"); // NOI18N
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Check.png"))); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setName("BtnAceptar"); // NOI18N
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAgregarAntropometristaLayout = new javax.swing.GroupLayout(pAgregarAntropometrista);
        pAgregarAntropometrista.setLayout(pAgregarAntropometristaLayout);
        pAgregarAntropometristaLayout.setHorizontalGroup(
            pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addGap(4, 4, 4)
                        .addComponent(BtnAceptar))
                    .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                        .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(ckSupervisor))
                            .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pAgregarAntropometristaLayout.setVerticalGroup(
            pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgregarAntropometristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pAgregarAntropometristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnAceptar)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAgregarAntropometrista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAgregarAntropometrista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        agregarAntropometrista();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        limpiarDatos();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VerAntropometristas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        //lblWarningCodigo.setVisible(false);
    }//GEN-LAST:event_txtCodigoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JCheckBox ckSupervisor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pAgregarAntropometrista;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void agregarAntropometrista(){
        if(validarDatos()){
            Antropometrista antrop = new Antropometrista();
            antrop.setCodigo(Integer.parseInt(this.txtCodigo.getText()));
            antrop.setNombre(this.txtNombre.getText());
            antrop.setTelefono(this.txtTelefono.getText());
            if(this.ckSupervisor.isSelected()){
                antrop.setSupervisor(1);
            }
            else{
                antrop.setSupervisor(0);
            }
            /*Agregar Antropometrista a la base de datos*/
            
            try{
                new DataBase().insertarAntropometrista(antrop);
                if(idRonda != -1){
                    insertarRondaAntropometrista(antrop);
                }
                JOptionPane.showMessageDialog(null, "Se agregó al antropometrista correctamente.");
                this.dispose();
                limpiarDatos();
            }
            catch(SQLException se){
                JOptionPane.showMessageDialog(null, 
                        "Ocurrió un error al ingresar el antropometrista. Intente de nuevo.\n\n"+se.getMessage());
            }
        }
        else{
            Error.mostrarMensajeError(this, "Ingrese los datos del antropometrista correctamente.",
                    "Registro de Antropometrista");
        }
    }
    
    public void limpiarDatos(){
        this.txtCodigo.setText("");
        this.txtNombre.setText("");
        this.txtTelefono.setText("");
        this.ckSupervisor.setSelected(false);
    }
    
    public boolean validarDatos(){
        if(!this.txtCodigo.getText().equals("") && TiposValidator.esNumero(txtCodigo) &&
                !this.txtNombre.getText().equals("") && !this.txtTelefono.getText().equals(""))
            return true;
        return false;
    }

    private void insertarRondaAntropometrista(Antropometrista antrop) {
        DataBase op = new DataBase();
        Iterator i = sujetos.iterator();
        Sujeto su;
        while(i.hasNext()){
            su = (Sujeto)i.next();
            try{
                op.insertarRondaAntropometrista(new RondaAntropometrista(su.getId(), Integer.valueOf(antrop.getCodigo()), idRonda));
            }
            catch(SQLException se){
                Error.mostrarMensajeError(this, "Ocurrió un error en la base de datos mientras"
                        + "se insertaba los datos a la ronda. \n\n"
                                + "MENSAJE: "+se.getMessage(), "Agregar Antropometrista");
                return;
            }
        }
    }

}
