/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softestandantrop;

import com.toedter.calendar.JDateChooser;
import java.awt.Frame;
import java.util.Date;
import java.util.Locale;
import javax.swing.ButtonGroup;

/**
 *
 * @author Luis
 */
public class AgregarEstandarizacion extends javax.swing.JDialog {
    JDateChooser fechaInicio;
    JDateChooser fechaFin;
    /**
     * Creates new form AgregarEstandarizacion
     */
    public AgregarEstandarizacion() {
        super(new Frame(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        fechaInicio = new JDateChooser(new Date());
        fechaInicio.setLocale(new Locale("es"));
        fechaInicio.setDateFormatString("dd/MM/yyyy");
        fechaInicio.setBounds(80, 63, 110, 20);
//        dateChooser.setPreferredSize(new Dimension(130, 20));
//        dateChooser.setFont(new Font("Verdana", Font.PLAIN, 10));
//        dateChooser.setDateFormatString("dd-MM-yyyy");
        fechaInicio.setVisible(true);
	AgregarEstandarizacion.add(fechaInicio);
        
        fechaFin = new JDateChooser(new Date());
        fechaFin.setLocale(new Locale("es"));
        fechaFin.setDateFormatString("dd/MM/yyyy");
        fechaFin.setBounds(80, 98, 110, 20);
//        dateChooser.setPreferredSize(new Dimension(130, 20));
//        dateChooser.setFont(new Font("Verdana", Font.PLAIN, 10));
//        dateChooser.setDateFormatString("dd-MM-yyyy");
        fechaFin.setVisible(true);
	AgregarEstandarizacion.add(fechaFin);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarEstandarizacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtencuesta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Estandarización");

        AgregarEstandarizacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Estandarización", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Encuesta:");

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Fecha Fin:");

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Check.png"))); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setName("BtnAceptar"); // NOI18N

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Delete.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setName("BtnCancelar"); // NOI18N

        jLabel4.setText("Nombre:");

        javax.swing.GroupLayout AgregarEstandarizacionLayout = new javax.swing.GroupLayout(AgregarEstandarizacion);
        AgregarEstandarizacion.setLayout(AgregarEstandarizacionLayout);
        AgregarEstandarizacionLayout.setHorizontalGroup(
            AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEstandarizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarEstandarizacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAceptar))
                    .addGroup(AgregarEstandarizacionLayout.createSequentialGroup()
                        .addGroup(AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(AgregarEstandarizacionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombre))
                            .addGroup(AgregarEstandarizacionLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtencuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarEstandarizacionLayout.setVerticalGroup(
            AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEstandarizacionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtencuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(AgregarEstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarEstandarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarEstandarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarEstandarizacion;
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtencuesta;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
