/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softestandantrop;

import DataBase.DataBase;
import Modelos.Antropometrista;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class VerAntropometristas extends javax.swing.JDialog {

    /**
     * Creates new form VerAntropometristas
     */
    public VerAntropometristas() {
        super(new Frame(), true);
        initComponents();
        
        DefaultTableModel modelo = new DefaultTableModel();
        jtAntropometristas.setModel(modelo);
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Supervisor");
        List<Antropometrista> antropometristas = null;
        try{
             antropometristas = new DataBase().getAllAntropometristas();
        }
        catch(SQLException se){
            Error.mostrarMensajeError(this, "Ocurrió un error en la base de datos mientras se obtenian los"
                    + "antropometristas. \n\n"
                                + "MENSAJE: "+se.getMessage(), "Edicion de Mediciones");
        }
        int fila = 0;
        for(Antropometrista an:antropometristas){
            ArrayList a = new ArrayList();
            a.add(an.getCodigo());
            a.add(an.getNombre());
            a.add(an.getTelefono());
            a.add(an.getSupervisor());
//                an.getCodigo(),an.getNombre(),an.getTelefono(),an.getSupervisor()};
            modelo.addRow(a.toArray());
//            jtAntropometristas.setValueAt(an.getCodigo(), fila, 0);
//            jtAntropometristas.setValueAt(an.getNombre(), fila, 1);
//            jtAntropometristas.setValueAt(an.getTelefono(), fila, 2);
//            jtAntropometristas.setValueAt(an.getSupervisor(), fila, 3);
            fila += 1;
        }
        jtAntropometristas.setModel(modelo);
        jtAntropometristas.updateUI();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Antropometristas = new javax.swing.JPanel();
        BtnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAntropometristas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Antropometristas ingresados");

        Antropometristas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Antropometristas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Check.png"))); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setName("BtnAceptar"); // NOI18N
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        jtAntropometristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Telefono", "Supervisor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtAntropometristas);

        javax.swing.GroupLayout AntropometristasLayout = new javax.swing.GroupLayout(Antropometristas);
        Antropometristas.setLayout(AntropometristasLayout);
        AntropometristasLayout.setHorizontalGroup(
            AntropometristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AntropometristasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AntropometristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AntropometristasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAceptar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        AntropometristasLayout.setVerticalGroup(
            AntropometristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AntropometristasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Antropometristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Antropometristas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Antropometristas;
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAntropometristas;
    // End of variables declaration//GEN-END:variables
}
